environment.name=prod

spring.datasource.url.1=jdbc:postgresql://db:5432/hibernate1
spring.datasource.username.1=hibernate1
spring.datasource.password.1=123456
spring.datasource.driver.1=org.postgresql.Driver

spring.datasource.url.2=jdbc:postgresql://db2:5432/hibernate2
spring.datasource.username.2=hibernate2
spring.datasource.password.2=123456
spring.datasource.driver.2=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#database.hibernate.schema_update=create

spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
database.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# App Properties
addenplus.app.jwtSecret= ======================AddenPlus=PROD===========================
addenplus.app.jwtExpirationMs=86400000


